---

- name: "Starting Configuration Remote Server."
  block:

    - name: START CONFIG LAB - Configurar failover_number en servera
      debug:
        msg: "* La variable failover_number es: {{ failover_number }} "
      when: inventory_hostname in groups['servera']

    - name: START CONFIG LAB - Cerrar todas las sesiones SSH activas en servera, excepto la de Ansible
      become: yes
      ansible.builtin.shell: |
        # Obtener la lista de procesos sshd relacionados con root y student
        sessions=$(ps -eo pid,cmd | grep 'sshd' | grep -v 'grep' | grep -vE '(root|student)@pts/\d+' | grep pts | awk '{print $1}')
        # Contar cuántas líneas hay en la salida
        num_sessions=$(echo "$sessions" | wc -l)
        # Si hay solo un proceso, no hacer nada
        if [ "$num_sessions" -eq 1 ]; then
          echo "Solo hay una sesión SSH activa. No se mata ningún proceso."
        else
          # Si hay más de uno, matar todos menos el último
          # Iterar sobre las líneas de salida excepto la última
          for pid in $(echo "$sessions" | head -n -1); do
            # Matar las sesiones SSH activas (de otros usuarios)
            kill -9 $pid 2>/dev/null || true
            logger -p local7.info -t "LAB-RH134" "simulate validate {{ failover_remote_project }}  process SSH kill : $pid  "
          done
        fi

      ignore_errors: yes  # No interrumpir la ejecución si alguna sesión no se puede matar

    - name: "START CONFIG LAB - Borrar historial de usuario student permanentemente"
      become_user: student
      ansible.builtin.shell: |
        truncate -s 0 ~/.bash_history
        history -c
        history -w
      args:
        executable: /bin/bash
       
    - name: "START CONFIG LAB - Borrar historial de root permanentemente"
      become: yes
      ansible.builtin.shell: |
        truncate -s 0 ~/.bash_history
        history -c
        history -w
      args:
        executable: /bin/bash
      
    - name: START CONFIG LAB - Forzar la actualización del historial user root
      become: yes
      ansible.builtin.shell:
        cmd: "history -a && history -n"

    - name: START CONFIG LAB - Forzar la actualización del historial user student
      become_user: student
      ansible.builtin.shell:
        cmd: "history -a && history -n"

    - name: "START CONFIG LAB - Eliminar archivo de history del bash  {{ ansible_env.HOME }}/.bash_history, usuario student "
      become_user: student
      ansible.builtin.file:
        path: "/home/student/.bash_history"
        state: absent
      ignore_errors: yes

    - name: "START CONFIG LAB - Eliminar archivo de history del bash  {{ ansible_env.HOME }}/.bash_history, usuario root "
      become: yes
      ansible.builtin.file:
        path: "/root/.bash_history"
        state: absent
      ignore_errors: yes

    - name: START CONFIG LAB - Limpiar el historial de bash user student
      become_user: student
      ansible.builtin.shell: "history -c "
      ignore_errors: yes

    - name: START CONFIG LAB - Limpiar el historial de bash user root
      become: yes
      ansible.builtin.shell: "history -c "
      ignore_errors: yes

    - name: "START CONFIG LAB - Remove /var/log/message-lab "
      become: yes
      ansible.builtin.file:
        path: "/var/log/message-lab"
        state: absent
        force: yes

    - name: "START CONFIG LAB - Reiniciar Rsyslog para cargar la nueva regla"
      ansible.builtin.systemd:
        name: rsyslog
        state: restarted

    - name: "START CONFIG LAB - Syslog inicia el Logger"
      become: yes
      ansible.builtin.shell:
        # Generamos la marca de tiempo y la enviamos a local7.info
        cmd: |
          HORA_ACTUAL=$(date +'%Y-%m-%d %H:%M:%S')
          logger -p local7.info -t "LAB-RH134" "Inicia el laboratorio {{ failover_remote_project }} hora_inicio=$HORA_ACTUAL"

    - name: "START CONFIG LAB - Remove directory validator: {{ failover_remote_validator_temp }} temporal"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_validator_temp }}"
        state: absent
        mode: 0775
        force: yes

    - name: "START CONFIG LAB - Create directory validator: {{ failover_remote_validator_temp }} temporal"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_validator_temp }}"
        state: directory
        mode: 0775
        force: yes

    - name: "START CONFIG LAB - Create directory validator: {{ failover_remote_validator_audit }} audit"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_validator_audit }}"
        state: directory
        mode: 0775
        force: yes

    - name: "START CONFIG LAB - Create directory os report file: {{ failover_remote_os_report }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_os_report }}"
        state: touch
        mode: 0775
        force: yes

    - name: "START CONFIG LAB - Ensure app workdir exists: {{ failover_remote_workdir_simulate }}/{{ failover_number }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_workdir_simulate }}/{{ failover_number }}"
        state: directory
        mode: 0775
        force: yes

    - name: "START CONFIG LAB - Ensure app workdir exists: {{ failover_remote_workdir_exam }}/{{ failover_number }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_workdir_exam }}/{{ failover_number }}"
        state: directory
        mode: 0775
        force: yes

    - name: "START CONFIG LAB - Syslog prepared start environment = {{ failover_remote_environment }} "
      become: yes
      ansible.builtin.shell:
        # Generamos la marca de tiempo y la enviamos a local7.info
        cmd: |
          logger -p local7.info -t "LAB-RH134" "Preparacion entorno listo para el review..."

  when: failover_remote_environment == "servera"

