---

- name: "Starting Configuration Remote Server."
  block:

    - name: IINIT CONFIG LAB - nstalando paquetes requeridos para el lab
      dnf:
        name: "{{ lab_remote_tools }}"
        state: present
      when: lab_remote_tools is defined

    - name: Crear archivo de configuración lab.conf
      copy:
        dest: /etc/rsyslog.d/lab.conf
        content: |
          local7.* /var/log/message-lab
          & stop
        owner: root
        group: root
        mode: '0644'

    - name: Reiniciar rsyslog
      service:
        name: rsyslog
        state: restarted

    - name: "INIT CONFIG LAB - Remove directory validator: {{ failover_remote_validator_temp }} temporal"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_validator_temp }}"
        state: absent
        mode: 0775
        force: yes

    - name: "INIT CONFIG LAB - Create directory validator: {{ failover_remote_validator_temp }} temporal"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_validator_temp }}"
        state: directory
        mode: 0775
        force: yes

    - name: "INIT CONFIG LAB - Ensure app workdir exists: {{ failover_remote_workdir_simulate }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_workdir_simulate }}"
        state: directory
        mode: 0775
        force: yes

    - name: "INIT CONFIG LAB - Ensure app workdir exists: {{ failover_remote_workdir_exam }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_remote_workdir_exam }}"
        state: directory
        mode: 0775
        force: yes

    - name: "INIT CONFIG LAB - Syslog prepared start environment = {{ failover_remote_environment }} "
      become: yes
      ansible.builtin.shell:
        cmd: |
          logger -p local7.info -t "LAB-RH134" "Configuracion Inicial de {{ failover_remote_environment }} ..."

  when: failover_remote_environment == "serverb"

