---

- name: "Starting Configuration Workstatiion"

  block:

    - name: IINIT CONFIG LAB - nstalando paquetes requeridos para el lab
      dnf:
        name: "{{ lab_tools }}"
        state: present
      when: lab_tools is defined

    - name: "INIT CONFIG LAB - Asegurar que atd está corriendo"
      become: yes
      ansible.builtin.service:
        name: atd
        state: started
        enabled: yes
    
    - name: "INIT CONFIG LAB - Create file /var/log/labtool.log"
      become: yes
      ansible.builtin.file:
        path: "/var/log/labtool.log"
        state: touch
        mode: 0775

    - name: "INIT CONFIG LAB - Create directory config: {{ failover_config }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_config }}"
        state: directory
        mode: 0775

    - name: "INIT CONFIG LAB - Validar si el archivo de configuración existe"
      ansible.builtin.stat:
        path: "{{ failover_config }}/config"
      register: config_file

    - name: "INIT CONFIG LAB - Escribir configuración"
      become: yes
      ansible.builtin.copy:
        dest: "{{ failover_config }}/config"
        content: |
          # Lab setup to expirate proccess to evaluate
          # This value is in minutes
          expiration_simulate=10

      when: not config_file.stat.exists
      ignore_errors: yes

    - name: Crear archivo de configuración lab.conf
      copy:
        dest: /etc/rsyslog.d/lab.conf
        content: |
          local7.* /var/log/message-lab
          & stop
        owner: root
        group: root
        mode: '0644'
          
    - name: Reiniciar rsyslog
      service:
        name: rsyslog
        state: restarted

    - name: "INIT CONFIG LAB - Ensure app workdir exists: {{ failover_workdir_simulate }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_workdir_simulate }}"
        state: directory
        mode: 0775
        force: yes

    - name: "INIT CONFIG LAB - Ensure app workdir exists: {{ failover_workdir_simulate_eval }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_workdir_simulate_eval }}"
        state: directory
        mode: 0775
        force: yes

    - name: "INIT CONFIG LAB - Ensure app workdir exists: {{ failover_workdir_exam }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_workdir_exam }}"
        state: directory
        mode: 0775
        force: yes

    - name: "INIT CONFIG LAB - Ensure app workdir exists: {{ failover_workdir_exam_eval }}"
      become: yes
      ansible.builtin.file:
        path: "{{ failover_workdir_exam_eval }}"
        state: directory
        mode: 0775
        force: yes

    - name: "INIT CONFIG LAB - Syslog prepared start environment = {{ failover_remote_environment }} "
      become: yes
      ansible.builtin.shell:
        cmd: |
          logger -p local7.info -t "LAB-RH134" "Configuracion Inicial de {{ failover_environment }} ..."
          
  when: failover_environment == "workstation"

