---

#- name: SIMULATE LAB - Reiniciar el sistema para velidar  SELINUX
#  ansible.builtin.reboot:
#    reboot_timeout: 600
#    test_command:  "getenforce"


- name: SIMULATE LAB - Cerrar todas las sesiones SSH activas en servera, excepto la de Ansible
  become: yes
  ansible.builtin.shell: |
    # Obtener la lista de procesos sshd relacionados con root y student
    sessions=$(ps -eo pid,cmd | grep 'sshd' | grep -v 'grep' | grep -vE '(root|student)@pts/\d+' | grep pts | awk '{print $1}')
    # Contar cuántas líneas hay en la salida
    num_sessions=$(echo "$sessions" | wc -l)
    # Si hay solo un proceso, no hacer nada
    if [ "$num_sessions" -eq 1 ]; then
      echo "Solo hay una sesión SSH activa. No se mata ningún proceso."
    else
      # Si hay más de uno, matar todos menos el último
      # Iterar sobre las líneas de salida excepto la última
      for pid in $(echo "$sessions" | head -n -1); do
        # Matar las sesiones SSH activas (de otros usuarios)
        kill -9 $pid 2>/dev/null || true
        logger -p local7.info -t "LAB-RH134" "simulate validate {{ failover_remote_project }}  process SSH kill : $pid  "
      done
    fi

  ignore_errors: yes  # No interrumpir la ejecución si alguna sesión no se puede matar


- name: SIMULATE LAB - Forzar la actualización del historial
  become: yes
  ansible.builtin.shell:
    cmd: "history -a && history -n"

- name: SIMULATE LAB - Establecer flag en Workstation si el lab está activo
  delegate_to: workstation
  ansible.builtin.file:
    path: "{{ failover_remote_validator_temp }}/active-simulate"
    state: touch
    mode: '0644'

- name: "SIMULATE LAB - Crear file validator: {{ failover_remote_validator_temp }}/simulate.log temporal"
  become: yes
  ansible.builtin.file:
    path: "{{ failover_remote_validator_temp }}/simulate.log"
    state: touch
    mode: 0644

- name: SIMULATE LAB - Leer el archivo /etc/selinux/config para verificar SELINUX=enforcing
  ansible.builtin.slurp:
    src: /etc/selinux/config
  register: config_file

- name: SIMULATE LAB - Log de éxito (SELINUX=enforcing encontrado)
  become: yes
  ansible.builtin.shell: 
    cmd: "echo '1:selinux:success:Enforcing' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: config_file.content | b64decode | regex_search('SELINUX=enforcing')
  changed_when: true

- name: SIMULATE LAB - Log de error (SELINUX=enforcing NO encontrado)
  become: yes
  ansible.builtin.shell: 
    cmd: "echo '1:selinux:failed:Enforcing' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: not (config_file.content | b64decode | regex_search('SELINUX=enforcing'))
  changed_when: true


- name: SIMULATE LAB - Verificar que getenforce devuelva "Enforcing"
  become: yes
  ansible.builtin.command:
    cmd: getenforce
  register: getenforce_output
  changed_when: false

- name: SIMULATE LAB - Validar que la salida de getenforce sea "Enforcing"
  become: yes
  ansible.builtin.shell:
    cmd: "echo '2:getenforce:success:Enforcing' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: getenforce_output.stdout == "Enforcing" 

- name: SIMULATE LAB - Validar que la salida de getenforce sea distinto "Enforcing"
  become: yes
  ansible.builtin.shell:
    cmd: "echo '2:getenforce:failed:Enforcing' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: getenforce_output.stdout != "Enforcing" 


- name: SIMULATE LAB - Obtener historial de comandos
  ansible.builtin.shell: |
    history -a  # Fuerza la escritura de la sesión actual al archivo
    cat /root/.bash_history
  register: history_output

- name: SIMULATE LAB - Escribir historial en archivo log
  become: yes
  ansible.builtin.copy:
    content: "{{ history_output.stdout }}"
    dest: "{{ failover_remote_validator_temp }}/history.log"
    mode: '0644'

- name: SIMULATE LAB - Validar si getenforce aparece correctamente en el historial
  become: yes
  ansible.builtin.shell:
    cmd: "echo '3:history:success:getenforce' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: history_output.stdout | regex_search('^getenforce', multiline=True)

- name: SIMULATE LAB - Validar si getenforce no aparece correctamente en el historial
  become: yes
  ansible.builtin.shell:
    cmd: "echo '3:history:failed:getenforce' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: not(history_output.stdout | regex_search('^getenforce', multiline=True))


- name: SIMULATE LAB - Validar si setenforce 1 aparece correctamente en el historial
  become: yes
  ansible.builtin.shell:
    cmd: "echo '4:history:success:setenforce 1' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: history_output.stdout | regex_search('^setenforce 1', multiline=True)

- name: SIMULATE LAB - Validar si setenforce 1 no aparece correctamente en el historial
  become: yes
  ansible.builtin.shell:
    cmd: "echo '4:history:failed:setenforce 1' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: not(history_output.stdout | regex_search('^setenforce 1', multiline=True))


- name: SIMULATE LAB - Validar si setenforce 0 aparece correctamente en el historial
  become: yes
  ansible.builtin.shell:
    cmd: "echo '5:history:success:setenforce 0' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: history_output.stdout | regex_search('^setenforce 0', multiline=True)

- name: SIMULATE LAB - Validar si setenforce 0 no aparece correctamente en el historial
  become: yes
  ansible.builtin.shell:
    cmd: "echo '5:history:failed:setenforce 0' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: not (history_output.stdout | regex_search('^setenforce 0', multiline=True))


- name: SIMULATE LAB - Validar si systecmctl reboot aparece correctamente en el historial
  become: yes
  ansible.builtin.shell:
    cmd: "echo '6:history:success:systemctl reboot' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: history_output.stdout | regex_search('^systemctl reboot', multiline=True)

- name: SIMULATE LAB - Validar si systecmctl reboot no aparece correctamente en el historial
  become: yes
  ansible.builtin.shell:
    cmd: "echo '6:history:failed:systecmctl reboot' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: not (history_output.stdout | regex_search('^systemctl reboot', multiline=True))



- name: SIMULATE LAB - Extraer la hora de inicio del archivo de log
  ansible.builtin.shell: |
    grep "Inicia el laboratorio" {{ failover_remote_rsyslog }} | tail -n 1 | awk -F'=' '{print $2}' | tr -d '")'
  register: raw_start_time
  changed_when: false

- name: SIMULATE LAB - Setear varriable de fecha para cargar al --since del journalctl
  set_fact:
    journal_start_time: "{{ raw_start_time.stdout }}"

- name: "SIMULATE LAB - Debug logs de journal_start_time {{ raw_start_time.stdout }}"
  ansible.builtin.debug:
    var: journal_start_time

- name: SIMULATE LAB - Obtener logs  del Journalctl desde el inicio del laboratorio
  ansible.builtin.shell:
    cmd: "journalctl -u systemd-logind --since '{{ journal_start_time }}' | grep 'The system will reboot now!'"
  register: reboot_output
  changed_when: false
  failed_when: false # Evita que falle si el grep no encuentra nada

- name: SIMULATE LAB - Debug logs desde el inicio del lab
  ansible.builtin.debug:
    var: reboot_output.stdout_lines

- name: SIMULATE LAB - Verificar Log si existe reboot en el journalclt
  ansible.builtin.shell:
    cmd: "echo '7:journalctl:success:The system will reboot now' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: "'The system will reboot now!' in reboot_output.stdout"
  changed_when: false
  failed_when: false # Evita que falle si el grep no encuentra nada

- name: SIMULATE LAB - Verificar Log si no existe reboot en el journalclt
  ansible.builtin.shell:
    cmd: "echo '7:journalctl:failed:The system will reboot now' >> {{ failover_remote_validator_temp }}/simulate.log"
  when: "'The system will reboot now!'not in reboot_output.stdout"
  changed_when: false
  failed_when: false # Evita que falle si el grep no encuentra nada
