---

#- name: SIMULATE LAB - Reiniciar el sistema para velidar  SELINUX
#  ansible.builtin.reboot:
#    reboot_timeout: 600
#    test_command:  "getenforce"


- name: SIMULATE LAB - Cerrar todas las sesiones SSH activas en servera, excepto la de Ansible
  become: yes
  ansible.builtin.shell: |
    # Obtener la lista de procesos sshd relacionados con root y student
    sessions=$(ps -eo pid,cmd | grep 'sshd' | grep -v 'grep' | grep -vE '(root|student)@pts/\d+' | grep pts | awk '{print $1}')
    # Contar cuántas líneas hay en la salida
    num_sessions=$(echo "$sessions" | wc -l)
    # Si hay solo un proceso, no hacer nada
    if [ "$num_sessions" -eq 1 ]; then
      echo "Solo hay una sesión SSH activa. No se mata ningún proceso."
    else
      # Si hay más de uno, matar todos menos el último
      # Iterar sobre las líneas de salida excepto la última
      for pid in $(echo "$sessions" | head -n -1); do
        # Matar las sesiones SSH activas (de otros usuarios)
        kill -9 $pid 2>/dev/null || true
        logger -p local7.info -t "LAB-RH134" "simulate validate {{ failover_remote_project }}  process SSH kill : $pid  "
      done
    fi

  ignore_errors: yes  # No interrumpir la ejecución si alguna sesión no se puede matar


- name: SIMULATE LAB - Forzar la actualización del historial
  become: yes
  ansible.builtin.shell:
    cmd: "history -a && history -n"

- name: SIMULATE LAB - Establecer flag en Workstation si el lab está activo
  delegate_to: workstation
  ansible.builtin.file:
    path: "{{ failover_remote_validator_temp }}/active-simulate"
    state: touch
    mode: '0644'

- name: "SIMULATE LAB - Crear file validator: {{ failover_remote_validator_temp }}/simulate.log temporal"
  become: yes
  ansible.builtin.file:
    path: "{{ failover_remote_validator_temp }}/simulate.log"
    state: touch
    mode: 0644

- name: "SIMULATE LAB - Leer configuración de SELinux"
  ansible.builtin.slurp:
    src: /etc/selinux/config
  register: selinux_raw

- name: "SIMULATE LAB - Procesar resultados de validación"
  set_fact:
    selinux_results: >-
      {%- set content = selinux_raw.content | b64decode -%}
      {%- if content | regex_search(item.regex) -%}
      1:selinux:success:{{ item.label }}
      {%- else -%}
      1:selinux:failed:{{ item.label }}
      {%- endif -%}
  loop: "{{ validator_conf_file }}"
  register: processed_lines

- name: "SIMULATE LAB - Registrar resultados en log"
  become: yes
  ansible.builtin.lineinfile:
    path: "{{ failover_remote_validator_temp }}/simulate.log"
    create: yes
    line: "{{ item.ansible_facts.selinux_results }}"
    mode: '0644'
  loop: "{{ processed_lines.results }}"

- name: SIMULATE LAB - Verificar que getenforce devuelva "Enforcing"
  become: yes
  ansible.builtin.command:
    cmd: getenforce
  register: getenforce_output
  changed_when: false

- name: SIMULATE LAB - Registrar resultado la salida de getenforce  en simulate.log
  become: yes
  ansible.builtin.shell:
    cmd: |
      {% set status = 'success' if getenforce_output.stdout == 'Enforcing' else 'failed' %}
      echo "2:getenforce:{{ status }}:Enforcing" >> {{ failover_remote_validator_temp }}/simulate.log

- name: SIMULATE LAB - Obtener historial de comandos
  ansible.builtin.shell: |
    history -a  # Fuerza la escritura de la sesión actual al archivo
    cat /root/.bash_history
  register: history_output

- name: SIMULATE LAB - Escribir historial en archivo log
  become: yes
  ansible.builtin.copy:
    content: "{{ history_output.stdout }}"
    dest: "{{ failover_remote_validator_temp }}/history.log"
    mode: '0644'

- name: SIMULATE LAB - Validar comandos en el historial
  ansible.builtin.lineinfile:
    path: "{{ failover_remote_validator_temp }}/simulate.log"
    create: yes
    line: >-
      {{ item.id }}:checked:{{ 'success' if (history_output.stdout | regex_search(item.regex, multiline=True)) else 'failed' }}:{{ item.label }}
  loop: "{{ validator_history }}"


- name: SIMULATE LAB - Extraer la hora de inicio del archivo de log
  ansible.builtin.shell: |
    grep "Inicia el laboratorio" {{ failover_remote_rsyslog }} | tail -n 1 | awk -F'=' '{print $2}' | tr -d '")'
  register: raw_start_time
  changed_when: false

- name: SIMULATE LAB - Setear varriable de fecha para cargar al --since del journalctl
  set_fact:
    journal_start_time: "{{ raw_start_time.stdout }}"

- name: "SIMULATE LAB - Debug logs de journal_start_time {{ raw_start_time.stdout }}"
  ansible.builtin.debug:
    var: journal_start_time

- name: SIMULATE LAB - Register Log del journalclt en la variables journal_output
  ansible.builtin.command:
    cmd: "journalctl -u systemd-logind --since '{{ journal_start_time }}'"
  register: journal_output
  changed_when: false
  failed_when: false

- name: SIMULATE LAB - Debug logs desde el inicio del lab
  ansible.builtin.debug:
    var: reboot_output.stdout_lines

- name: SIMULATE LAB - Verificar Log si existe el patron en el journalclt
  ansible.builtin.lineinfile:
    path: "{{ failover_remote_validator_temp }}/simulate.log"
    line: "{{ item.id }}:journalctl:{{ 'success' if item.label in journal_output.stdout else 'failed' }}:{{ item.label }}"
    create: yes
  loop: "{{ validator_journal }}"
  changed_when: false

- name: "SIMULATE LAB - Crear  journal.log en workstation con el contenido leído de la variable journal_output"
  delegate_to: workstation
  ansible.builtin.copy:
    content: "{{ journal_output.stdout }}"
    dest: "{{ failover_remote_validator_temp }}/journal.log"
    mode: '0644'

- name: "SIMULATE LAB - Leer contenido del simulate.log en servera"
  ansible.builtin.slurp:
    src: "{{ failover_remote_validator_temp }}/simulate.log"
  register: remote_log

- name: "SIMULATE LAB - Crear el archivo en workstation con el contenido leído"
  delegate_to: workstation
  # become: yes  # Actívalo si necesitas permisos de root en workstation
  ansible.builtin.copy:
    content: "{{ remote_log['content'] | b64decode }}"
    dest: "{{ failover_remote_validator_temp }}/simulate.log"
    mode: '0644'

- name: "SIMULATE LAB - Leer contenido del history.log en servera"
  ansible.builtin.slurp:
    src: "{{ failover_remote_validator_temp }}/history.log"
  register: history_log

- name: "SIMULATE LAB - Crear el archivo history.log en workstation con el contenido leído"
  delegate_to: workstation
  ansible.builtin.copy:
    content: "{{ history_log['content'] | b64decode }}"
    dest: "{{ failover_remote_validator_temp }}/history.log"
    mode: '0644'

- name: "SIMULATE LAB - Obtener ID de secuencia desde workstation"
  delegate_to: workstation
  ansible.builtin.command: cat "{{ failover_remote_workspace }}/{{ failover_remote_project }}/sequence/sequence.ini"
  register: lab_sequence_raw
  changed_when: false

- name: "SIMULATE LAB - Establecer ID de laboratorio como fact"
  set_fact:
    lab_id: "{{ lab_sequence_raw.stdout | trim }}"

- name: "SIMULATE LAB - Sincronizar resultados a la ruta final en workstation"
  delegate_to: workstation
  become: yes
  ansible.builtin.copy:
    src: "/tmp/{{ failover_remote_project }}"
    dest: "{{ failover_remote_workdir_simulate }}/{{ lab_id }}/"
    remote_src: yes
    mode: '0755'
