---

- name: "START VALIDDATE LAB - Eliminar archivo de history del bash  {{ ansible_env.HOME }}/.bash_history, using shell: {{ ansible_env.SHELL }} "
  become: yes
  ansible.builtin.file:
    path: "root/.bash_history"
    state: absent  
  ignore_errors: yes
  #when: ansible_env.SHELL == "/bin/bash"

- name: START VALIDDATE LAB - Limpiar el historial de bash
  become: yes
  ansible.builtin.shell: "history -c "
  ignore_errors: yes

- name: START VALIDDATE LAB - Verificar que el archivo /etc/selinux/config sea diferente de SELINUX=enforcing
  ansible.builtin.slurp:
    src: /etc/selinux/config
  register: config_file
  changed_when: false

- name: START VALIDDATE LAB - Establecer SELINUX=enforcing en /etc/selinux/config
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'
    state: present
  when: "'SELINUX=enforcing' not in config_file.content | b64decode" 

- name: START VALIDDATE LAB - Reiniciar el sistema si SELINUX ha cambiado a Enforcing
  ansible.builtin.reboot:
    reboot_timeout: 600
    test_command:  "getenforce"
  when: "'SELINUX=enforcing' not in config_file.content | b64decode"
