---

failover_mode: "{{ failover_mode  || default('start') }}" 
failover_environment: null                         # workstation, servera serverb
failover_user: student
failover_group: student
failover_rsyslog: /var/log/message-lab
failover_config: /etc/lab-rh134
failover_config_home: ~/lab-rh134
failover_workspace: '/usr/local/.labs'
failover_project:                                         # lab <failover_mode> <failover_project> 
failover_validator_temp: "/tmp/{{ failover_project }}"
failover_workdir_simulate: "{{ failover_workspace }}/{{  failover_project }}/simulate"
failover_workdir_simulate_eval: "{{ failover_workspace }}/{{ failover_project }}/simulate-eval"
failover_workdir_exam: "{{ failover_workspace }}/{{  failover_project }}/exam"
failover_workdir_exam_eval: "{{ failover_workspace }}/{{ failover_project }}/exam-eval"
failover_sequence: "{{ failover_workspace }}/{{ failover_project }}/sequence"
failover_sequence_file: "{{ failover_sequence }}/sequence.ini"

failover_remote_environment: null                        # workstation, servera serverb
failover_remote_user: student
failover_remote_group: student
failover_remote_rsyslog: /var/log/message-lab
failover_remote_workspace: '/usr/local/.labs'
failover_remote_project:                                   # lab <failover_mode> <failover_project> 
failover_remote_validator_temp: "/tmp/{{ failover_remote_project }}"
failover_remote_workdir_simulate: "{{ failover_remote_workspace }}/{{ failover_remote_project }}/simulate"
failover_remote_workdir_exam: "{{ failover_remote_workspace }}/{{ failover_remote_project }}/exam"

