---

- name: selinux opsmode
  hosts: workstation
  gather_facts: no
  become: true
  vars: 
    failover_mode: "start"
  roles:
    - role: selinux-opsmode
      failover_project: selinux-opsmode               # lab <failover_mode> <failover_project>
      failover_environment: "workstation"               # workstation, servera serverb 
      failover_user: root 
      failover_group: root


- name: selinux opsmode
  hosts: servera
  gather_facts: no
  become: true
  vars: 
    failover_mode: "start"
  roles:
    - role: selinux-opsmode
      failover_remote_project: selinux-opsmode
      failover_remote_environment: "servera"              # workstation, servera serverb 
      failover_remote_user: root
      failover_remote_group: root
      validator_conf_file:
        - { label: 'Permissive', regex: 'SELINUX=permissive' , weight: 15}
        - { label: 'Targeted', regex: 'SELINUXTYPE=targeted' , weight: 15}
      validator_history:
        - { id: 3, label: "getenforce", regex: "^getenforce" , weight: 10}
        - { id: 4, label: "setenforce 1", regex: "^setenforce 1" , weight: 10}
        - { id: 5, label: "setenforce 0", regex: "^setenforce 0" , weight: 10}
        - { id: 6, label: "systemctl reboot", regex: "^systemctl reboot" , weight: 10}
      validator_journal:
        - { id: "7", label: "The system will reboot now!" , weight: 10}


        
