galaxy_info:
  role_name: selinux-opsmode
  namespace: middleware_automation
  author: Alexander Aguilar Torrico
  description: configuration.
  company: Failover BO.

  license: Apache License 2.0

  min_ansible_version: "2.9"

  platforms:
   - name: EL
     versions:
     - 9
     - 10

  galaxy_tags:
    - redhat
    - rhel
