---

- name: START VALIDATE LAB - Obtener lista de IDs de tareas de AT
  become_user: student
  shell: "atq | awk '{print $1}'"
  register: at_jobs
  changed_when: false

- name: START VALIDATE LAB - Eliminar cada tarea encontrada
  become_user: student
  shell: "atrm {{ item }}"
  loop: "{{ at_jobs.stdout_lines }}"
  when: at_jobs.stdout_lines | length > 0
  register: result

- name: START VALIDATE LAB - Detener el servicio atd
  ansible.builtin.systemd_service:
    name: atd
    state: stopped

- name: START VALIDATE LAB - Vaciar el archivo de secuencia .SEQ para reiniciar el ID a 0
  ansible.builtin.file:
    path: /var/spool/at/.SEQ
    state: touch    # Asegura que el archivo exista
    modification_time: preserve
    access_time: preserve
    # El truco: Para vaciarlo por completo usamos una redirección o el módulo copy con contenido vacío
    
- name: START VALIDATE LAB - Forzar que quede en 0 bytes
  ansible.builtin.copy:
    content: ""
    dest: /var/spool/at/.SEQ
    mode: '0600' # Permisos por defecto del sistema para este archivo

- name: START VALIDATE LAB - Iniciar el servicio atd con la cola limpia
  ansible.builtin.systemd_service:
    name: atd
    state: started

- name: START VALIDATE LAB - Verificar y remover archivos generados
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ validator_start_file }}"
  ignore_errors: yes
